### PR TITLE
147129 -  Bess builder service read queue message 

### PR DESCRIPTION
**Pull request by abhijeet14992**
This PR consists changes of [PBI : 147129](https://dev.azure.com/ukhydro/Exchange%20Set%20Service/_workitems/edit/147129)

### CODE REVIEW

**Review by shirinbt14926 — APPROVED** [review]
LGTM

**Review by harshal11869 — APPROVED** [review]
Looks Good.

**Review by amogh14893 — APPROVED** [review]
Changes looks good to me . approved.

**Review by JiviteshT — APPROVED** [review]
Looks good

**Pull request merged**
